#!/bin/bash

echo "----------------------------------------------------------------------------------------------------------------"
echo ""
echo "	• ▌ ▄ ·.  ▄▄▄· ▐▄• ▄ 		User:		$(whoami)"
echo "	·██ ▐███▪▐█ ▀█  █▌█▌▪		Hostname:	$(hostname)"
echo "	▐█ ▌▐▌▐█·▄█▀▀█  ·██· 		Kernel:		$(uname -r)"
echo "	██ ██▌▐█▌▐█ ▪▐▌▪▐█·█▌		Shell:		$SHELL"	
echo "	▀▀  █▪▀▀▀ ▀  ▀ •▀▀ ▀▀		CPU:		$(sed -n 's/^model name[ \t]*: *//p' /proc/cpuinfo | uniq | sed ':a;N;$!ba;s/\n/, /g')"
echo ""
echo "----------------------------------------------------------------------------------------------------------------"

echo "Executing tasks:"

if [ "$EUID" -ne 0 ]
  then echo "Please run as root to install apps"
else
	wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | apt-key add -
	apt -y install apt-transport-https
	echo "deb https://download.sublimetext.com/ apt/stable/" | tee /etc/apt/sources.list.d/sublime-text.list
	apt-get update
	apt -y install \
		curl && \
		git-all && \
		htop && \
		python3 && \
		python3-pip && \
		rxvt-unicode && \
		sublime-text && \
		tmux
fi

echo "Setting up git"

git config --global user.name "Maksymilian Potok"
git config --global user.email makspotok@gmail.com

echo "Changing default terminal"

update-alternatives --set x-terminal-emulator /usr/bin/urxvt

echo "Done!"
